# syntax version.
version: "3.7"


services:

  ktcent:
    build:
      context: ""
      dockerfile: Dockerfile
    expose:
      - "1978"
      - "18801"
    command:
      - "-plsv"
      - "/usr/local/libexec/libktmsgpack.so"
      - "-plex"
      - "port=18801#thread=8"
      - "/data/db/data.kch#opts=c#zcomp=lzo#bnum=100000000#dfunit=8"
    ports:
      - 1978:1978
      - 18801:18801

